import { useSearchParams } from "react-router-dom";

export default function InvoiceView() {
  const [params] = useSearchParams();
  const inv = params.get("inv") || "";

  return (
    <div style={{ fontFamily: "'Courier New', Courier, monospace", maxWidth: 780, margin: "40px auto", textAlign: "center" }}>
      <h2>Invoice #{inv}</h2>
      <p style={{ marginTop: 16, fontSize: 14, color: "#555" }}>
        This invoice was generated by <strong>Swati Tours &amp; Transport</strong>.
      </p>
      <p style={{ marginTop: 8, fontSize: 13, color: "#888" }}>
        For full invoice details, please contact the office or open the application.
      </p>
      <div style={{ marginTop: 30, padding: 20, border: "2px solid #000", display: "inline-block" }}>
        <div style={{ fontWeight: "bold", fontSize: 17 }}>SWATI TOURS &amp; TRANSPORT</div>
        <div style={{ fontSize: 11, marginTop: 4 }}>ROOM NO 4, RAM NAGIN TIWARI BHUVAN ASALFA VILLAGE,</div>
        <div style={{ fontSize: 11 }}>NEAR SHRI RAM APTGHATKOPAR WEST MUMBAI 400084</div>
        <div style={{ fontSize: 12, fontWeight: "bold", marginTop: 4 }}>UAM MH19D0152647 / PAN BSNPP7564G</div>
        <div style={{ fontSize: 16, fontWeight: "bold", marginTop: 12, background: "#FFFF00", display: "inline-block", padding: "4px 20px" }}>
          Invoice No: {inv}
        </div>
      </div>
    </div>
  );
}
